server.port: 7001

spring.application.name: product

---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/product
    username: root
    password: root

server.port: 8080

