server.port: 7001

spring.application.name: product

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


---
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/product
    username: root
    password: root

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

